### ISSUE TITLE
Activating the panel using "Tab" messes up the map

### ISSUE THREAD

**Issue by Drachenkaetzchen** [VinylFox/ExtJS.ux.GMapPanel#1]
Hi,

I've got the GMapPanel within a form. If the user hits "tab" (e.g. from a textfield), the Map has an odd behaviour. It is hard to explain, the map stays the same, but the map's controls and the Google Logo shift up by about half the size of the map. 

Or this is probably caused by the address change itself; I'm not sure, as it doesn't happen all the time.

Here's a small video to illustrate that behavior: http://www.youtube.com/watch?v=ZNFkvA6sEeA

**Comment by VinylFox** [comment]
Can you provide me with the code used to layout the form field and map together?

**Comment by Drachenkaetzchen** [comment]
I debugged a bit more because my test case didn't reproduce the behavior. Finally I found out that it was neither the tab nor the centering, but my additional call to hideMarkers() which messes up. Any idea what the reason could be?

**Comment by Drachenkaetzchen** [comment]
I might have been hit by a bug in the latest chromium codebase - because the bug virtually occurs when it likes to. No issues in Firefox so far. I will leave this open unless I can be sure that this isn't a bug within the GMapPanel.

**Comment by VinylFox** [comment]
So I guess we can close this one out, until you can reproduce it.
