### ISSUE TITLE
"String.format not a function" - in Firefox 3.6.10

### ISSUE THREAD

**Issue by elchiapp** [VinylFox/ExtJS.ux.GMapPanel#11]
I didn't try with other "old" browsers but I wanted to report that (at line 692) String.format can't be recognized because of the lack of the ExtJS namespace. 

Resolved by replacing String.format with Ext.String.format.

**Comment by VinylFox** [comment]
Thanks for the report, will fix asap.

**Comment by VinylFox** [comment]
Thanks again - fixed.

**Comment by elchiapp** [comment]
Thank you for being so quick! :)

**Comment by VinylFox** [comment]
The thanks should go to you, you did all the work figuring out what was wrong and how to fix it.
