### ISSUE TITLE
'apiready' is never fired.

### ISSUE THREAD

**Issue by emb** [VinylFox/ExtJS.ux.GMapPanel#4]
I was using Ext.data.Store to load markers, however, I found out that 'apiready' was never fired.

**Comment by VinylFox** [comment]
Yeah, I'm not using the 'apiready' event yet, but if your adding markers then you will want to use the 'mapready' event instead.

**Comment by emb** [comment]
Yeah true, but again 'mapready' never gets fired if you do not set Markers or a Center. In my fork  emb/ExtJS.ux.GMapPanel@69fb9b6ccf8dde2e1ffb I added a line around 310 "this.fireEvent('apiready', this, this.gmap);"

My editor would seem to have 'untabified' and converted it to a unix file :-/

**Comment by VinylFox** [comment]
You must always set a center, this is a requirement of the Google Maps API.
