### ISSUE TITLE
Add show / hide polylines 

### ISSUE THREAD

**Issue by Mazzo** [VinylFox/ExtJS.ux.GMapPanel#6]
hi, VinylFox

I needed to be able to hide and show polylines besides markers...
so I added two methods to the class.

I have code ready if you want.
(for ext3 with map v3)

**Comment by Mazzo** [comment]
code:

// private
    hidePolylines : function(){
        Ext.each(this.cache.polyline, function(mrk){
            mrk.setMap(null);
        },this);
    },
    // private
    showPolylines : function(){
        Ext.each(this.cache.polyline, function(mrk){
                mrk.setMap(this.getMap());
            }, this);
    },

**Comment by VinylFox** [comment]
That appears to be the code from the /examples/charts/charts.html example code at line 250.

I think that only a handful of people would use this and it's such a simple thing to do that the small number of people that would use this function could just add this code into their own functions.
